name: core
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  adaptive_dialog: ^1.5.0+1
  cupertino_icons: ^1.0.2
  fast_immutable_collections: ^7.3.1
  flutter:
    sdk: flutter
  fpdart: ^0.0.14
  freezed_annotation: ^2.0.3
  geocoding: ^2.0.2
  geolocator: ^8.1.1
  get_storage: ^2.0.3
  google_place: ^0.4.7
  json_annotation: ^4.4.0
  location: ^4.3.0
  permission_handler: ^8.3.0
  rxdart: ^0.27.3
  supabase_flutter: ^0.3.0
  uuid: ^3.0.5

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  hive_generator: ^1.1.2
  json_serializable: null

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
